url: "https://france.hp.gbif-staging.org/" # the base hostname & protocol for your staging site, e.g. https://hp-example.gbif-staging.org

matomo:
  enabled: true
  url: "https://matomo.test.mnhn.fr/"
  container: "container_tZuHu0EU.js"
  siteId: "19" 
